// <auto-generated />
using System;
using Infrastructure.Data.Telegram;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Telegram.Migrations
{
    [DbContext(typeof(TelegramContext))]
    [Migration("20230228014506_Notifications")]
    partial class Notifications
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApplicationCore.Entities.Telegram.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("datetime2");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserCreateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserCreateId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Telegram.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("datetime2");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplited")
                        .HasColumnType("bit");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserCreateProblemId")
                        .HasColumnType("int");

                    b.Property<int?>("UserGetProblemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserCreateProblemId");

                    b.HasIndex("UserGetProblemId");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Telegram.TelegramUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NotificationHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Telegram.Answer", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Telegram.Problem", "Problem")
                        .WithMany("Answers")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Telegram.TelegramUser", "UserCreate")
                        .WithMany("Answers")
                        .HasForeignKey("UserCreateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Problem");

                    b.Navigation("UserCreate");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Telegram.Problem", b =>
                {
                    b.HasOne("ApplicationCore.Entities.Telegram.TelegramUser", "UserCreateProblem")
                        .WithMany("Problems")
                        .HasForeignKey("UserCreateProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationCore.Entities.Telegram.TelegramUser", "UserGetProblem")
                        .WithMany("GetProblems")
                        .HasForeignKey("UserGetProblemId");

                    b.Navigation("UserCreateProblem");

                    b.Navigation("UserGetProblem");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Telegram.Problem", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("ApplicationCore.Entities.Telegram.TelegramUser", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("GetProblems");

                    b.Navigation("Problems");
                });
#pragma warning restore 612, 618
        }
    }
}
